// Serialise the roster of trained neural opponents into src/ai/nn/models.ts —
// the dependency-free data the browser imports so each trained model is a
// selectable opponent in the start dialog. This is ADDITIVE: it never touches
// src/ai/nn/weights.ts (the tiered "Neural - Easy/Medium/Hard" champion) nor the
// heuristic CPUs.
//
//   vite-node training/emit-models.ts            # regenerate src/ai/nn/models.ts
//
// What it bundles (only genomes that LOAD against the live 63-dim policy):
//   - p2-champion  (rust-trainer/checkpoints/champion.json, 63-dim, as-is)
//   - v57-champion (training/checkpoints/champion-v57.json.bak, 57-dim, PORTED)
//   - HoF #1..#N   (rust-trainer/checkpoints/hof.json, 63-dim, as-is)
//
// Porting 57→63: the 6 Phase-2 features (local indices 10–15) are appended at
// the END of the input vector, so the old 57 features are exactly today's input
// indices 0–56. A 57-dim net therefore loads byte-for-byte identically once its
// first-layer weight rows are padded with 6 trailing zeros per output neuron —
// the new inputs multiply by zero, so the scored output is unchanged.

import * as fs from 'node:fs';
import * as path from 'node:path';
import { Genome, paramCount } from '../src/ai/nn/mlp';
import { POLICY_INPUT_DIM } from '../src/ai/nn/policy';

const REPO = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const OUT = path.join(REPO, 'src/ai/nn/models.ts');

interface ModelSpec {
  id: string;
  label: string;
  note: string;
  file: string;
  hofIndex?: number; // if set, read element [hofIndex] of a genome array
}

/** Pad a [fromDim,h,...] policy genome up to POLICY_INPUT_DIM by appending zero
 *  input-weight columns to the first layer (the 6 new features are last). */
function padToPolicyDim(g: Genome): Genome {
  const fromDim = g.arch[0];
  if (fromDim === POLICY_INPUT_DIM) return g;
  if (fromDim > POLICY_INPUT_DIM) {
    throw new Error(`genome input dim ${fromDim} > policy dim ${POLICY_INPUT_DIM}; cannot pad`);
  }
  const nout = g.arch[1];
  const extra = POLICY_INPUT_DIM - fromDim;
  const out: number[] = [];
  // First layer: nout neurons, each with `fromDim` weights → append `extra` zeros.
  for (let j = 0; j < nout; j++) {
    const base = j * fromDim;
    for (let i = 0; i < fromDim; i++) out.push(g.params[base + i]);
    for (let i = 0; i < extra; i++) out.push(0);
  }
  // First-layer biases, then every later layer's params, all unchanged.
  const tailStart = fromDim * nout;
  for (let k = tailStart; k < g.params.length; k++) out.push(g.params[k]);
  const padded: Genome = { arch: [POLICY_INPUT_DIM, ...g.arch.slice(1)], params: out };
  if (padded.params.length !== paramCount(padded.arch)) {
    throw new Error(`pad produced ${padded.params.length} params, expected ${paramCount(padded.arch)}`);
  }
  return padded;
}

function loadGenome(spec: ModelSpec): Genome {
  const raw = JSON.parse(fs.readFileSync(path.join(REPO, spec.file), 'utf8'));
  const g: Genome = spec.hofIndex !== undefined ? raw[spec.hofIndex] : raw;
  if (!Array.isArray(g?.arch) || !Array.isArray(g?.params)) {
    throw new Error(`${spec.file}${spec.hofIndex !== undefined ? `[${spec.hofIndex}]` : ''} is not a genome`);
  }
  return padToPolicyDim(g);
}

function main(): void {
  const specs: ModelSpec[] = [
    { id: 'p2-champion', label: 'Trained: P2 Champion (~15% vs hard)', note: 'Phase-2 spatial-local champion; current deploy', file: 'rust-trainer/checkpoints/champion.json' },
    { id: 'v57-champion', label: 'Trained: v57 Champion (~27% vs hard)', note: 'Pre-Phase2 champion, ported 57→63 (zero-padded)', file: 'training/checkpoints/champion-v57.json.bak' },
  ];
  // Hall-of-Fame roster (10 diverse 63-dim genomes from the P2 run).
  const hofPath = path.join(REPO, 'rust-trainer/checkpoints/hof.json');
  if (fs.existsSync(hofPath)) {
    const hof = JSON.parse(fs.readFileSync(hofPath, 'utf8')) as Genome[];
    for (let i = 0; i < hof.length; i++) {
      specs.push({ id: `hof-${i + 1}`, label: `Trained: Hall of Fame #${i + 1}`, note: `P2 hall-of-fame genome ${i + 1}/${hof.length}`, file: 'rust-trainer/checkpoints/hof.json', hofIndex: i });
    }
  }

  const models = specs.map((s) => {
    const g = loadGenome(s);
    if (g.arch[0] !== POLICY_INPUT_DIM) throw new Error(`${s.id}: arch ${g.arch[0]} != ${POLICY_INPUT_DIM}`);
    return { id: s.id, label: s.label, note: s.note, genome: g };
  });

  const lines = models.map(
    (m) =>
      `  { id: ${JSON.stringify(m.id)}, label: ${JSON.stringify(m.label)}, note: ${JSON.stringify(m.note)}, ` +
      `genome: { arch: ${JSON.stringify(m.genome.arch)}, params: [${m.genome.params.map((v) => +v.toFixed(6)).join(',')}] } },`,
  );

  const body = `// AUTO-GENERATED by training/emit-models.ts — do not edit by hand.
//
// The roster of trained neural opponents, each selectable in the start dialog as
// "Trained: <name>". Pure data shipped to the browser (no runtime dependency).
// ADDITIVE: separate from weights.ts (the tiered Neural-Easy/Medium/Hard champion)
// and the heuristic CPUs. Regenerate via training/emit-models.ts.

import type { Genome } from './mlp';

export interface NeuralModel {
  /** Stable id; the player difficulty for this opponent is \`model:<id>\`. */
  id: string;
  /** Label shown in the start-dialog opponent dropdown. */
  label: string;
  /** Provenance / tooltip. */
  note: string;
  /** The trained network (always padded to the live 63-dim policy input). */
  genome: Genome;
}

export const NEURAL_MODELS: NeuralModel[] = [
${lines.join('\n')}
];

export const NEURAL_MODELS_BY_ID: Record<string, NeuralModel> = Object.fromEntries(
  NEURAL_MODELS.map((m) => [m.id, m]),
);
`;
  fs.writeFileSync(OUT, body);
  console.log(`wrote ${path.relative(REPO, OUT)} — ${models.length} models:`);
  for (const m of models) console.log(`  ${m.id.padEnd(14)} arch=${JSON.stringify(m.genome.genome?.arch ?? m.genome.arch)} params=${m.genome.params.length}`);
}

main();
