// Serialise a trained genome + tier configs into src/ai/nn/weights.ts — the
// dependency-free artifact the browser imports. Used by calibrate.ts (and to
// stamp an initial placeholder so the client compiles before training lands).
//
//   vite-node training/emit-weights.ts -- <genome.json> [outPath]

import * as fs from 'node:fs';
import * as path from 'node:path';
import { Genome } from '../src/ai/nn/mlp';
import { TierConfig } from '../src/ai/nn/candidates';
import { HARD_CONFIG, MEDIUM_CONFIG, EASY_CONFIG, TIER_SEARCH } from '../src/ai/nn/tiers';
import type { SearchConfig } from '../src/ai/nn/search';
import type { ValueNet } from '../src/ai/nn/value';

export interface TierSet {
  easy: TierConfig;
  medium: TierConfig;
  hard: TierConfig;
}

export interface WeightsExtras {
  /** Optional learned value net for value-leaf MCTS. */
  valueNet?: ValueNet;
  /** Optional per-tier MCTS configs (defaults to TIER_SEARCH if omitted). */
  search?: { easy: SearchConfig; medium: SearchConfig; hard: SearchConfig };
}

export function writeWeights(
  genome: Genome,
  tiers: TierSet,
  meta: Record<string, unknown>,
  outPath = 'src/ai/nn/weights.ts',
  extras: WeightsExtras = {},
): void {
  const params = genome.params.map((v) => +v.toFixed(6));
  const search = extras.search ?? TIER_SEARCH;
  const valueNetLine = extras.valueNet
    ? `  valueNet: ${JSON.stringify(extras.valueNet)},\n`
    : '';
  const body = `// AUTO-GENERATED by training/emit-weights.ts — do not edit by hand.
//
// Trained policy-network weights for the neural CPU opponents, plus the
// per-difficulty tier configs and (optionally) the value net + MCTS search
// configs. Pure data: imported by src/ai/nn/index.ts and shipped to the browser
// (no runtime dependency). Regenerate via training/calibrate.ts after (re)training.

import { TierConfig } from './candidates';
import type { SearchConfig } from './search';
import type { ValueNet } from './value';

export interface NeuralWeights {
  arch: number[];
  params: number[];
  tiers: { easy: TierConfig; medium: TierConfig; hard: TierConfig };
  meta: Record<string, unknown>;
  valueNet?: ValueNet;
  search?: { easy: SearchConfig; medium: SearchConfig; hard: SearchConfig };
}

export const NEURAL_WEIGHTS: NeuralWeights = {
  arch: ${JSON.stringify(genome.arch)},
  tiers: {
    easy: ${JSON.stringify(tiers.easy)},
    medium: ${JSON.stringify(tiers.medium)},
    hard: ${JSON.stringify(tiers.hard)},
  },
  meta: ${JSON.stringify(meta)},
${valueNetLine}  search: {
    easy: ${JSON.stringify(search.easy)},
    medium: ${JSON.stringify(search.medium)},
    hard: ${JSON.stringify(search.hard)},
  },
  params: [${params.join(',')}],
};
`;
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, body);
}

export const DEFAULT_TIERS: TierSet = { easy: EASY_CONFIG, medium: MEDIUM_CONFIG, hard: HARD_CONFIG };

// CLI entry: emit weights from a genome JSON file.
const direct = process.argv[1] && process.argv[1].endsWith('emit-weights.ts');
if (direct) {
  const inPath = process.argv[2] ?? process.argv[process.argv.indexOf('--') + 1];
  if (!inPath) {
    console.error('usage: vite-node training/emit-weights.ts -- <genome.json> [outPath]');
    process.exit(1);
  }
  const genome: Genome = JSON.parse(fs.readFileSync(inPath, 'utf8'));
  const out = process.argv[3] ?? 'src/ai/nn/weights.ts';
  writeWeights(genome, DEFAULT_TIERS, { source: inPath, generatedFrom: 'cli' }, out);
  console.log(`wrote ${out} (${genome.params.length} params)`);
}
