// Serialise two trained Rust SpatialNet weights.json files into the
// dependency-free roster artifact src/ai/nn/models_spatial_roster.ts — the data
// the browser imports for the multi-model "AlphaZero" / "AlphaZero XL" opponents.
//
// Mirrors training/emit-weights.ts (MLP) but for the spatial CNN: each Rust JSON
// maps 1:1 onto the TS `SpatialWeights` shape used by SpatialNetTS. The only
// difference is the extra `pool` key the Rust serde emits (a global-avg-pool
// marker with no parameters), which the TS forward does not read — we strip it
// so the roster matches the existing models_spatial.ts champion format exactly.
//
//   vite-node training/emit-spatial-roster.ts
//
// (paths to the two nets are fixed below; edit ROSTER_SPEC to add/replace nets.)

import * as fs from 'node:fs';
import * as path from 'node:path';

interface RosterSpec {
  id: string;
  label: string;
  note: string;
  /** Path to the Rust SpatialNet weights.json (relative to repo root). */
  source: string;
}

// The two trained nets to bundle. exit2-best = SMALL (no conv3, "AlphaZero").
// large2-best = LARGE (residual conv3, wider dims, "AlphaZero XL").
const ROSTER_SPEC: RosterSpec[] = [
  {
    id: 'kalevi',
    label: 'AlphaZero',
    note: 'Trained CNN champion (small arch, ~10.3k params, no residual conv3). Net-greedy / deploy-MCTS spatial policy.',
    source: 'rust-trainer/exit2-best.json',
  },
  {
    id: 'gunnar',
    label: 'AlphaZero XL',
    note: 'Trained CNN champion (large arch, ~54.9k params, residual conv3, wider d1=32/d=48/hv=hp=64). Net-greedy / deploy-MCTS spatial policy.',
    source: 'rust-trainer/large2-best.json',
  },
];

const OUT_PATH = 'src/ai/nn/models_spatial_roster.ts';

/** Strip the Rust-only `pool` marker so the JSON matches TS `SpatialWeights`. */
function toSpatialWeights(raw: Record<string, unknown>): Record<string, unknown> {
  const { pool: _pool, ...rest } = raw;
  return rest;
}

function paramCount(w: Record<string, unknown>): number {
  let n = 0;
  for (const v of Object.values(w)) {
    if (v && typeof v === 'object') {
      const wt = (v as { weights?: number[]; bias?: number[] });
      if (Array.isArray(wt.weights)) n += wt.weights.length;
      if (Array.isArray(wt.bias)) n += wt.bias.length;
    }
  }
  return n;
}

function emit(): void {
  const entries = ROSTER_SPEC.map((spec) => {
    const raw = JSON.parse(fs.readFileSync(spec.source, 'utf8')) as Record<string, unknown>;
    const weights = toSpatialWeights(raw);
    return { spec, weights, params: paramCount(weights) };
  });

  const items = entries
    .map(({ spec, weights }) => `  {
    id: ${JSON.stringify(spec.id)},
    label: ${JSON.stringify(spec.label)},
    note: ${JSON.stringify(spec.note)},
    weights: ${JSON.stringify(weights)},
  },`)
    .join('\n');

  const sources = entries
    .map(({ spec, params }) => `//   ${spec.id} (${spec.label}) <- ${spec.source}  (~${params} params)`)
    .join('\n');

  const body = `// AUTO-GENERATED by training/emit-spatial-roster.ts — do NOT edit by hand.
//
// Roster of trained CNN AlphaZero opponents bundled for in-browser deploy, each
// loaded by spatial_net.ts (SpatialNetTS) and reachable in the start dialog /
// createModelController as the difficulty string \`model:<id>\`. The single
// headline champion in models_spatial.ts is unchanged (it stays the default
// fallback). Regenerate via: vite-node training/emit-spatial-roster.ts
//
// Sources:
${sources}

import type { SpatialWeights } from './spatial_net';

export interface SpatialRosterModel {
  /** Difficulty id; selected in-game as \`model:<id>\`. */
  id: string;
  /** Human-readable opponent name shown in the start dialog. */
  label: string;
  /** Short description of the net. */
  note: string;
  /** Forward-only SpatialNet weights (Rust serde JSON minus the \`pool\` marker). */
  weights: SpatialWeights;
}

export const SPATIAL_ROSTER: SpatialRosterModel[] = [
${items}
];

export const SPATIAL_ROSTER_BY_ID: Record<string, SpatialRosterModel> =
  Object.fromEntries(SPATIAL_ROSTER.map((m) => [m.id, m]));
`;

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, body);
  const summary = entries.map((e) => `${e.spec.id} (~${e.params} params)`).join(', ');
  console.log(`wrote ${OUT_PATH}: ${summary}`);
}

emit();
